/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab1_franciscosantos;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_personal = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_edad = new javax.swing.JTextField();
        tf_id = new javax.swing.JTextField();
        cb_sexo = new javax.swing.JComboBox<>();
        tf_horaE = new javax.swing.JTextField();
        cb_estado = new javax.swing.JComboBox<>();
        tf_ocupacion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_horaS = new javax.swing.JTextField();
        tf_TT = new javax.swing.JTextField();
        tf_sueldo = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        tf_contraseña = new javax.swing.JPasswordField();
        bt_SavePersonal = new javax.swing.JButton();
        jd_familiar = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        tf_nombreF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tf_altura = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tf_edadF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tf_peso = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_idF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cb_sexoF = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cb_estadoF = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_trabajo = new javax.swing.JTextField();
        bt_SaveFamiliar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_usuarioF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_contraseñaF = new javax.swing.JPasswordField();
        cb_rol = new javax.swing.JComboBox<>();
        jd_registro = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_VerUsuario = new javax.swing.JTextField();
        bt_ingresar = new javax.swing.JButton();
        tf_VerContraseña = new javax.swing.JPasswordField();
        jd_kim = new javax.swing.JDialog();
        tab_kim = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cb_registrados = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        cb_ListaPersonas = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        bt_eliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        tf_nombre1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tf_edad1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cb_sexo1 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        cb_estado1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jd_normal = new javax.swing.JDialog();
        jd_zapatos = new javax.swing.JDialog();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jd_ropa = new javax.swing.JDialog();
        jd_hogar = new javax.swing.JDialog();
        jl_personal = new javax.swing.JLabel();
        jl_familiar = new javax.swing.JLabel();
        jl_registrar = new javax.swing.JLabel();

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel3.setText("ID");

        jLabel4.setText("Sexo");

        jLabel5.setText("Estado");

        jLabel6.setText("Ocupacion");

        jLabel7.setText("Hora Entrada ");

        jLabel8.setText("Hora Salida");

        jLabel9.setText("Tiempo Trabajando");

        jLabel10.setText("Sueldo");

        jLabel11.setText("Usuario");

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", " " }));
        cb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexoActionPerformed(evt);
            }
        });

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "Divorciado", " " }));

        jLabel12.setText("Contaseña");

        bt_SavePersonal.setText("Guardar");
        bt_SavePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_SavePersonalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_personalLayout = new javax.swing.GroupLayout(jd_personal.getContentPane());
        jd_personal.getContentPane().setLayout(jd_personalLayout);
        jd_personalLayout.setHorizontalGroup(
            jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_personalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_personalLayout.createSequentialGroup()
                        .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombre)
                                .addComponent(tf_edad)
                                .addComponent(tf_id)
                                .addComponent(cb_estado, 0, 152, Short.MAX_VALUE))
                            .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_personalLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(56, 56, 56)
                                .addComponent(tf_horaS, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_personalLayout.createSequentialGroup()
                                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_TT)
                                    .addComponent(tf_sueldo)
                                    .addComponent(tf_usuario)
                                    .addComponent(tf_contraseña))))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jd_personalLayout.createSequentialGroup()
                        .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_ocupacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_horaE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_SavePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        jd_personalLayout.setVerticalGroup(
            jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_personalLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_horaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(tf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_personalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_horaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_SavePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel13.setText("Nombre");

        jLabel14.setText("Altura");

        jLabel15.setText("Edad");

        jLabel16.setText("Peso");

        jLabel17.setText("ID");

        tf_idF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idFActionPerformed(evt);
            }
        });

        jLabel19.setText("Sexo");

        cb_sexoF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", " " }));
        cb_sexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexoFActionPerformed(evt);
            }
        });

        jLabel21.setText("Estado");

        cb_estadoF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "Divorciado", " " }));

        jLabel23.setText("Rol");

        jLabel24.setText("Trabajo");

        bt_SaveFamiliar.setText("Guardar");
        bt_SaveFamiliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_SaveFamiliarMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Agregar Familiar");

        jLabel18.setText("Usuario");

        jLabel20.setText("Contaseña");

        cb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Madre", "Padre", "Hermana", "Hermano", "Esposo" }));

        javax.swing.GroupLayout jd_familiarLayout = new javax.swing.GroupLayout(jd_familiar.getContentPane());
        jd_familiar.getContentPane().setLayout(jd_familiarLayout);
        jd_familiarLayout.setHorizontalGroup(
            jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_familiarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_familiarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_nombreF)
                            .addComponent(tf_edadF)
                            .addComponent(tf_idF)
                            .addComponent(cb_estadoF, 0, 152, Short.MAX_VALUE)
                            .addComponent(cb_sexoF, 0, 152, Short.MAX_VALUE)
                            .addComponent(cb_rol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_familiarLayout.createSequentialGroup()
                                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel16))
                                .addGap(33, 33, 33)
                                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_SaveFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_familiarLayout.createSequentialGroup()
                                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_usuarioF)
                                    .addComponent(tf_contraseñaF)))))
                    .addGroup(jd_familiarLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        jd_familiarLayout.setVerticalGroup(
            jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_familiarLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_nombreF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(tf_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_edadF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tf_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_idF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(tf_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_familiarLayout.createSequentialGroup()
                        .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cb_sexoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cb_estadoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_familiarLayout.createSequentialGroup()
                        .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_usuarioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tf_contraseñaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jd_familiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_SaveFamiliar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(cb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Log In");

        jLabel26.setText("Usuario");

        jLabel27.setText("Contraseña");

        bt_ingresar.setText("Ingresar");
        bt_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ingresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registroLayout = new javax.swing.GroupLayout(jd_registro.getContentPane());
        jd_registro.getContentPane().setLayout(jd_registroLayout);
        jd_registroLayout.setHorizontalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(64, 64, 64)
                        .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_VerUsuario)
                            .addComponent(tf_VerContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(jd_registroLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jd_registroLayout.setVerticalGroup(
            jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registroLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_VerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jd_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_VerContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Agregar Zapatos");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Agregar Ropa");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Agregar Hogar");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel35)
                .addGap(68, 68, 68)
                .addComponent(jLabel36)
                .addGap(61, 61, 61)
                .addComponent(jLabel37)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        tab_kim.addTab("Agregar Objetos", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        tab_kim.addTab("Mensajeria", jPanel1);

        cb_registrados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_registrados, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(cb_registrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        tab_kim.addTab("No Leidos", jPanel2);

        jt_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "ID", "Estado Civil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_personas);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Personas");

        cb_ListaPersonas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ListaPersonasItemStateChanged(evt);
            }
        });

        jLabel29.setText("Personas");

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cb_ListaPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel29)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ListaPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        tab_kim.addTab("Personas", jPanel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel30.setText("Nombre");

        jLabel31.setText("Edad");

        jLabel32.setText("ID");

        tf_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id1ActionPerformed(evt);
            }
        });

        jLabel33.setText("Sexo");

        cb_sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", " " }));
        cb_sexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexo1ActionPerformed(evt);
            }
        });

        jLabel34.setText("Estado");

        cb_estado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "Divorciado", " " }));

        jButton1.setText("Modificar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombre1)
                                .addComponent(tf_edad1)
                                .addComponent(tf_id1)
                                .addComponent(cb_estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(tf_edad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cb_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(cb_estado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        tab_kim.addTab("Modificar Personas", jPanel4);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        tab_kim.addTab("Modificar Objetos", jPanel5);

        javax.swing.GroupLayout jd_kimLayout = new javax.swing.GroupLayout(jd_kim.getContentPane());
        jd_kim.getContentPane().setLayout(jd_kimLayout);
        jd_kimLayout.setHorizontalGroup(
            jd_kimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_kim)
        );
        jd_kimLayout.setVerticalGroup(
            jd_kimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab_kim)
        );

        javax.swing.GroupLayout jd_normalLayout = new javax.swing.GroupLayout(jd_normal.getContentPane());
        jd_normal.getContentPane().setLayout(jd_normalLayout);
        jd_normalLayout.setHorizontalGroup(
            jd_normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_normalLayout.setVerticalGroup(
            jd_normalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel38.setText("Color");

        jLabel39.setText("Descripcion");

        jLabel40.setText("Marca");

        jLabel41.setText("Tamaño");

        jLabel42.setText("Calidad");

        jLabel43.setText("Precio");

        jLabel44.setText("Dueño");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        javax.swing.GroupLayout jd_zapatosLayout = new javax.swing.GroupLayout(jd_zapatos.getContentPane());
        jd_zapatos.getContentPane().setLayout(jd_zapatosLayout);
        jd_zapatosLayout.setHorizontalGroup(
            jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_zapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43)
                    .addComponent(jLabel41)
                    .addComponent(jLabel40)
                    .addComponent(jLabel39)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jTextField6)
                        .addComponent(jTextField7)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jd_zapatosLayout.setVerticalGroup(
            jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_zapatosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel38)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jd_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jd_ropaLayout = new javax.swing.GroupLayout(jd_ropa.getContentPane());
        jd_ropa.getContentPane().setLayout(jd_ropaLayout);
        jd_ropaLayout.setHorizontalGroup(
            jd_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_ropaLayout.setVerticalGroup(
            jd_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_hogarLayout = new javax.swing.GroupLayout(jd_hogar.getContentPane());
        jd_hogar.getContentPane().setLayout(jd_hogarLayout);
        jd_hogarLayout.setHorizontalGroup(
            jd_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_hogarLayout.setVerticalGroup(
            jd_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_personal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_personal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_personal.setText("Agregar Personal");
        jl_personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personalMouseClicked(evt);
            }
        });

        jl_familiar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_familiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_familiar.setText("Agregar Familiares");
        jl_familiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_familiarMouseClicked(evt);
            }
        });

        jl_registrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_registrar.setText("Registrarse");
        jl_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_familiar)
                    .addComponent(jl_personal, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jl_personal)
                .addGap(72, 72, 72)
                .addComponent(jl_familiar)
                .addGap(64, 64, 64)
                .addComponent(jl_registrar)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jl_personalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personalMouseClicked
        jd_personal.pack();
        jd_personal.setModal(true);
        jd_personal.setVisible(true);
        jd_personal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jl_personalMouseClicked

    private void jl_familiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_familiarMouseClicked
        jd_familiar.pack();
        jd_familiar.setModal(true);
        jd_familiar.setVisible(true);
        jd_familiar.setLocationRelativeTo(null);
    }//GEN-LAST:event_jl_familiarMouseClicked

    private void jl_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_registrarMouseClicked
        jd_registro.pack();
        jd_registro.setModal(true);
        jd_registro.setVisible(true);
        jd_registro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jl_registrarMouseClicked

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed

    }//GEN-LAST:event_tf_idActionPerformed

    private void cb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexoActionPerformed

    }//GEN-LAST:event_cb_sexoActionPerformed

    private void bt_SavePersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_SavePersonalMouseClicked
        Personal p = new Personal(tf_ocupacion.getText(), tf_horaE.getText(), tf_horaS.getText(), Integer.parseInt(tf_TT.getText()), Integer.parseInt(tf_sueldo.getText()), tf_nombre.getText(), Integer.parseInt(tf_edad.getText()), Integer.parseInt(tf_id.getText()), cb_sexo.getSelectedItem().toString(), cb_estado.getSelectedItem().toString(), tf_usuario.getText(), tf_contraseña.getText());
        personas.add(p);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
        modelo.addElement(p);
        cb_ListaPersonas.setModel(modelo);
        //
        JOptionPane.showMessageDialog(null, "Se guardo la persona con exito");
        tf_ocupacion.setText("");
        tf_horaE.setText("");
        tf_horaS.setText("");
        tf_TT.setText("");
        tf_sueldo.setText("");
        tf_nombre.setText("");
        tf_edad.setText("");
        tf_id.setText("");
        cb_sexo.setSelectedIndex(0);
        cb_estado.setSelectedIndex(0);
        tf_usuario.setText("");
        tf_contraseña.setText("");
    }//GEN-LAST:event_bt_SavePersonalMouseClicked

    private void tf_idFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idFActionPerformed

    private void cb_sexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sexoFActionPerformed

    private void bt_SaveFamiliarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_SaveFamiliarMouseClicked
        if (contFam >= 0) {
            if (cb_rol.getSelectedItem().toString().equals("Padre") && dad > 0) {
                Familiares f = new Familiares(cb_rol.getSelectedItem().toString(), tf_trabajo.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_nombreF.getText(), Integer.parseInt(tf_edadF.getText()), Integer.parseInt(tf_idF.getText()), cb_sexoF.getSelectedItem().toString(), cb_estadoF.getSelectedItem().toString(), tf_usuarioF.getText(), tf_contraseñaF.getText());
                personas.add(f);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
                modelo.addElement(f);
                cb_ListaPersonas.setModel(modelo);
                dad--;
                contFam--;
                JOptionPane.showMessageDialog(null, "Se guardo la persona con exito");
            }
            if (cb_rol.getSelectedItem().toString().equals("Madre") && mom > 0) {
                Familiares f = new Familiares(cb_rol.getSelectedItem().toString(), tf_trabajo.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_nombreF.getText(), Integer.parseInt(tf_edadF.getText()), Integer.parseInt(tf_idF.getText()), cb_sexoF.getSelectedItem().toString(), cb_estadoF.getSelectedItem().toString(), tf_usuarioF.getText(), tf_contraseñaF.getText());
                personas.add(f);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
                modelo.addElement(f);
                cb_ListaPersonas.setModel(modelo);
                mom--;
                contFam--;
                JOptionPane.showMessageDialog(null, "Se guardo la persona con exito");
            }
            if (cb_rol.getSelectedItem().toString().equals("Esposo") && husb > 0) {
                Familiares f = new Familiares(cb_rol.getSelectedItem().toString(), tf_trabajo.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_nombreF.getText(), Integer.parseInt(tf_edadF.getText()), Integer.parseInt(tf_idF.getText()), cb_sexoF.getSelectedItem().toString(), cb_estadoF.getSelectedItem().toString(), tf_usuarioF.getText(), tf_contraseñaF.getText());
                personas.add(f);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
                modelo.addElement(f);
                cb_ListaPersonas.setModel(modelo);
                husb--;
                contFam--;
                JOptionPane.showMessageDialog(null, "Se guardo la persona con exito");
            }
            if (cb_rol.getSelectedItem().toString().equals("Hermano") && bro > 0) {
                Familiares f = new Familiares(cb_rol.getSelectedItem().toString(), tf_trabajo.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_nombreF.getText(), Integer.parseInt(tf_edadF.getText()), Integer.parseInt(tf_idF.getText()), cb_sexoF.getSelectedItem().toString(), cb_estadoF.getSelectedItem().toString(), tf_usuarioF.getText(), tf_contraseñaF.getText());
                personas.add(f);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
                modelo.addElement(f);
                cb_ListaPersonas.setModel(modelo);
                bro--;
                contFam--;
                JOptionPane.showMessageDialog(null, "Se guardo la persona con exito");
            }
            if (cb_rol.getSelectedItem().toString().equals("Hermana") && bro > 0) {
                Familiares f = new Familiares(cb_rol.getSelectedItem().toString(), tf_trabajo.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_nombreF.getText(), Integer.parseInt(tf_edadF.getText()), Integer.parseInt(tf_idF.getText()), cb_sexoF.getSelectedItem().toString(), cb_estadoF.getSelectedItem().toString(), tf_usuarioF.getText(), tf_contraseñaF.getText());
                personas.add(f);
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
                modelo.addElement(f);
                cb_ListaPersonas.setModel(modelo);
                sis--;
                contFam--;
                JOptionPane.showMessageDialog(null, "Se guardo la persona con exito");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No puede exceder la cantidad de familiares");
        }
        cb_rol.setSelectedIndex(0);
        tf_trabajo.setText("");
        tf_altura.setText("");
        tf_peso.setText("");
        tf_nombreF.setText("");
        tf_edadF.setText("");
        tf_idF.setText("");
        cb_sexoF.setSelectedIndex(0);
        cb_estadoF.setSelectedIndex(0);
        tf_usuarioF.setText("");
        tf_contraseñaF.setText("");
    }//GEN-LAST:event_bt_SaveFamiliarMouseClicked
    /*personas.add(new Familiares(cb_rol.getSelectedItem().toString(), tf_trabajo.getText(), Double.parseDouble(tf_altura.getText()), Double.parseDouble(tf_peso.getText()), tf_nombreF.getText(), Integer.parseInt(tf_edadF.getText()), Integer.parseInt(tf_idF.getText()), cb_sexoF.getSelectedItem().toString(), cb_estadoF.getSelectedItem().toString(), tf_usuarioF.getText(), tf_contraseñaF.getText()));
            JOptionPane.showMessageDialog(null,"Se guardo la persona con exito");
            cb_rol.setSelectedIndex(0);
            tf_trabajo.setText("");
            tf_altura.setText("");
            tf_peso.setText("");
            tf_nombreF.setText("");
            tf_edadF.setText("");
            tf_idF.setText("");
            cb_sexoF.setSelectedIndex(0);
            cb_estadoF.setSelectedIndex(0);
            tf_usuarioF.setText("");
            tf_contraseñaF.setText("");*/
    private void bt_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ingresarMouseClicked
        if (nombre.equals(tf_VerUsuario.getText()) && contra.equals(tf_VerContraseña.getText())) {
            JOptionPane.showMessageDialog(null, "//// Bienvenida Kim ////");
            UserAct = nombre;
            jd_kim.pack();
            jd_kim.setModal(true);
            jd_kim.setVisible(true);
            jd_kim.setLocationRelativeTo(null);
        } else {
            for (Personas t : personas) {
                if (t.getUsuario().equals(tf_VerUsuario.getText()) && t.getContraseña().equals(tf_VerContraseña.getText())) {
                    JOptionPane.showMessageDialog(null, "Bienvenido " + t.getNombre());
                    UserAct = t.getNombre();
                    jd_normal.pack();
                    jd_normal.setModal(true);
                    jd_normal.setVisible(true);
                    jd_normal.setLocationRelativeTo(null);
                }
            }
        }
    }//GEN-LAST:event_bt_ingresarMouseClicked

    private void cb_ListaPersonasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ListaPersonasItemStateChanged
        if (evt.getStateChange() == 2) {
            Personas s = (Personas) cb_ListaPersonas.getSelectedItem();
            Object[] newrow = {
                s.getNombre(),
                s.getEdad(),
                s.getId(),
                s.getEstado()
            };
            DefaultTableModel modelo = (DefaultTableModel) jt_personas.getModel();
            modelo.addRow(newrow);
            jt_personas.setModel(modelo);
            
        }
    }//GEN-LAST:event_cb_ListaPersonasItemStateChanged

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        if (cb_ListaPersonas.getSelectedIndex() >= 0) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_ListaPersonas.getModel();
            modelo.removeElementAt(cb_ListaPersonas.getSelectedIndex());
            cb_ListaPersonas.setModel(modelo);
        }
        if (jt_personas.getSelectedRow() >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) jt_personas.getModel();
            modelo.removeRow(jt_personas.getSelectedRow());
            jt_personas.setModel(modelo);
        }
        for (Personas t : personas) {
            if (cb_ListaPersonas.getSelectedItem().toString().equals(t.getNombre())) {
                personas.remove(t);
            }
        }
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void tf_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id1ActionPerformed

    private void cb_sexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_sexo1ActionPerformed

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        jd_zapatos.pack();
        jd_zapatos.setModal(true);
        jd_zapatos.setVisible(true);
        jd_zapatos.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        jd_ropa.pack();
        jd_ropa.setModal(true);
        jd_ropa.setVisible(true);
        jd_ropa.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        jd_hogar.pack();
        jd_hogar.setModal(true);
        jd_hogar.setVisible(true);
        jd_hogar.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel37MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_SaveFamiliar;
    private javax.swing.JButton bt_SavePersonal;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JComboBox<String> cb_ListaPersonas;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_estado1;
    private javax.swing.JComboBox<String> cb_estadoF;
    private javax.swing.JComboBox<String> cb_registrados;
    private javax.swing.JComboBox<String> cb_rol;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JComboBox<String> cb_sexo1;
    private javax.swing.JComboBox<String> cb_sexoF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JDialog jd_familiar;
    private javax.swing.JDialog jd_hogar;
    private javax.swing.JDialog jd_kim;
    private javax.swing.JDialog jd_normal;
    private javax.swing.JDialog jd_personal;
    private javax.swing.JDialog jd_registro;
    private javax.swing.JDialog jd_ropa;
    private javax.swing.JDialog jd_zapatos;
    private javax.swing.JLabel jl_familiar;
    private javax.swing.JLabel jl_personal;
    private javax.swing.JLabel jl_registrar;
    private javax.swing.JTable jt_personas;
    private javax.swing.JTabbedPane tab_kim;
    private javax.swing.JTextField tf_TT;
    private javax.swing.JPasswordField tf_VerContraseña;
    private javax.swing.JTextField tf_VerUsuario;
    private javax.swing.JTextField tf_altura;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JPasswordField tf_contraseñaF;
    private javax.swing.JTextField tf_edad;
    private javax.swing.JTextField tf_edad1;
    private javax.swing.JTextField tf_edadF;
    private javax.swing.JTextField tf_horaE;
    private javax.swing.JTextField tf_horaS;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_idF;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombreF;
    private javax.swing.JTextField tf_ocupacion;
    private javax.swing.JTextField tf_peso;
    private javax.swing.JTextField tf_sueldo;
    private javax.swing.JTextField tf_trabajo;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuarioF;
    // End of variables declaration//GEN-END:variables
    ArrayList<Personas> personas = new ArrayList();
    ArrayList<Objetos> objetos = new ArrayList();
    String nombre = "Kim";
    String contra = "dash";
    String UserAct;
    int contFam = 8;
    int sis = 4;
    int bro = 1;
    int dad = 1;
    int mom = 1;
    int husb = 1;
}
